CREATE TABLE questions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  question TEXT,
  multi TINYINT(1) UNSIGNED DEFAULT 0,
  answer1 TEXT DEFAULT NULL,
  answer2 TEXT DEFAULT NULL,
  answer3 TEXT DEFAULT NULL,
  answer4 TEXT DEFAULT NULL,
  answer5 TEXT DEFAULT NULL,
  answer6 TEXT DEFAULT NULL,
  answer7 TEXT DEFAULT NULL
);

CREATE TABLE results (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  question_id INT UNSIGNED,
  answer TEXT,
  other_text TEXT,
  FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE ON UPDATE CASCADE
  );
